"""
SQLAlchemy models for Voice Notes MVP.
Maps Python classes to PostgreSQL tables with pgvector support.
"""

import uuid
from datetime import datetime
from sqlalchemy import (
    Column, String, Text, Integer, BigInteger, Boolean, DateTime,
    ForeignKey, ARRAY, Index, func
)
from sqlalchemy.dialects.postgresql import UUID, JSONB, INET, CITEXT, TSVECTOR
from sqlalchemy.orm import relationship
from pgvector.sqlalchemy import Vector

from database.config import Base


class User(Base):
    """User model for authentication and authorization."""
    __tablename__ = 'users'

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email = Column(CITEXT, unique=True, nullable=False, index=True)
    password_hash = Column(Text, nullable=False)
    password_algo = Column(String(50), default='argon2')
    full_name = Column(Text)
    created_at = Column(DateTime(timezone=True), default=func.now())
    updated_at = Column(DateTime(timezone=True), default=func.now(), onupdate=func.now())

    # Relationships
    voice_notes = relationship("VoiceNote", back_populates="user", cascade="all, delete-orphan")
    chat_histories = relationship("ChatHistory", back_populates="user")
    header_chat_histories = relationship("HeaderChatHistory", back_populates="user", cascade="all, delete-orphan")

    def to_dict(self, include_sensitive=False):
        """Convert to dictionary for JSON serialization."""
        data = {
            'id': str(self.id),
            'email': self.email,
            'full_name': self.full_name,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
        }
        if include_sensitive:
            data['password_hash'] = self.password_hash
        return data


class VoiceNote(Base):
    """Voice note/recording model with transcripts and AI-generated content."""
    __tablename__ = 'voice_notes'

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='SET NULL'), index=True)
    parent_id = Column(UUID(as_uuid=True), ForeignKey('voice_notes.id', ondelete='CASCADE'), index=True)
    title = Column(Text)

    # Transcripts
    transcript = Column(Text)
    transcript_cleaned = Column(Text)

    # AI-generated content
    summary = Column(Text)
    meeting_notes = Column(Text)
    main_points = Column(Text)
    todo_list = Column(Text)
    email_draft = Column(Text)
    subnotes_summary = Column(Text)

    # File information
    file_url = Column(Text)
    file_name = Column(Text)
    file_size_bytes = Column(BigInteger)
    audio_path = Column(Text)  # legacy

    # Status and metadata
    status = Column(String(50), default='processing', index=True)
    duration_seconds = Column(Integer)
    note_metadata = Column('metadata', JSONB)  # images, links, etc. (column name 'metadata', attribute name 'note_metadata')

    # Full-text search vector (auto-generated by trigger)
    search_vector = Column(TSVECTOR)

    # Timestamps
    created_at = Column(DateTime(timezone=True), default=func.now(), index=True)
    updated_at = Column(DateTime(timezone=True), default=func.now(), onupdate=func.now())

    # Relationships
    user = relationship("User", back_populates="voice_notes")
    parent = relationship("VoiceNote", remote_side=[id], backref="subnotes")
    chunks = relationship("NoteChunk", back_populates="note", cascade="all, delete-orphan")
    chat_histories = relationship("ChatHistory", back_populates="note", cascade="all, delete-orphan")

    def to_dict(self, include_content=True):
        """Convert to dictionary for JSON serialization."""
        data = {
            'id': str(self.id),
            'user_id': str(self.user_id) if self.user_id else None,
            'parent_id': str(self.parent_id) if self.parent_id else None,
            'title': self.title,
            'status': self.status,
            'file_url': self.file_url,
            'file_name': self.file_name,
            'file_size_bytes': self.file_size_bytes,
            'audio_path': self.audio_path,
            'duration_seconds': self.duration_seconds,
            'metadata': self.note_metadata,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
        }

        if include_content:
            data.update({
                'transcript': self.transcript,
                'transcript_cleaned': self.transcript_cleaned,
                'summary': self.summary,
                'meeting_notes': self.meeting_notes,
                'main_points': self.main_points,
                'todo_list': self.todo_list,
                'email_draft': self.email_draft,
                'subnotes_summary': self.subnotes_summary,
            })

        # Add legacy fields for backward compatibility
        if self.transcript_cleaned:
            data['clean_transcript'] = self.transcript_cleaned
        if self.file_url:
            data['audio_url'] = self.file_url

        return data


class NoteChunk(Base):
    """Text chunks with vector embeddings for semantic search."""
    __tablename__ = 'note_chunks' 

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    note_id = Column(UUID(as_uuid=True), ForeignKey('voice_notes.id', ondelete='CASCADE'), nullable=False, index=True)
    chunk_index = Column(Integer, nullable=False)
    text = Column(Text, nullable=False)
    chunk_metadata = Column('metadata', JSONB)  # column name 'metadata', attribute name 'chunk_metadata'
    embedding = Column(Vector(1536))  # OpenAI text-embedding-3-small dimension (1536)
    embedding_model = Column(Text, default='text-embedding-3-small')
    embedding_created_at = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True), default=func.now())

    # Relationships
    note = relationship("VoiceNote", back_populates="chunks")

    __table_args__ = (
        Index('idx_note_chunks_unique', 'note_id', 'chunk_index', unique=True),
    )

    def to_dict(self):
        """Convert to dictionary for JSON serialization."""
        return {
            'id': str(self.id),
            'note_id': str(self.note_id),
            'chunk_index': self.chunk_index,
            'text': self.text,
            'metadata': self.chunk_metadata,
            'embedding_model': self.embedding_model,
            'embedding_created_at': self.embedding_created_at.isoformat() if self.embedding_created_at else None,
            'created_at': self.created_at.isoformat() if self.created_at else None,
        }


class ChatHistory(Base):
    """Chat history for Ask AI feature (note-specific conversations)."""
    __tablename__ = 'chat_history'

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    note_id = Column(UUID(as_uuid=True), ForeignKey('voice_notes.id', ondelete='CASCADE'), nullable=False, index=True)
    user_id = Column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='SET NULL'))
    question = Column(Text, nullable=False)
    answer = Column(Text, nullable=False)
    created_at = Column(DateTime(timezone=True), default=func.now(), index=True)

    # Relationships
    note = relationship("VoiceNote", back_populates="chat_histories")
    user = relationship("User", back_populates="chat_histories")

    def to_dict(self):
        """Convert to dictionary for JSON serialization."""
        return {
            'id': str(self.id),
            'note_id': str(self.note_id),
            'user_id': str(self.user_id) if self.user_id else None,
            'question': self.question,
            'answer': self.answer,
            'timestamp': self.created_at.timestamp() if self.created_at else None,
            'created_at': self.created_at.isoformat() if self.created_at else None,
        }


class HeaderChatHistory(Base):
    """Header Ask AI history (general conversations not tied to specific notes)."""
    __tablename__ = 'header_chat_history'

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), ForeignKey('users.id', ondelete='SET NULL'), index=True)
    rec_id = Column(Text, index=True)  # Recording ID that this chat is associated with
    title = Column(Text)
    messages = Column(JSONB, nullable=False)  # [{question, answer, timestamp}, ...]
    created_at = Column(DateTime(timezone=True), default=func.now(), index=True)
    updated_at = Column(DateTime(timezone=True), default=func.now(), onupdate=func.now())

    # Relationships
    user = relationship("User", back_populates="header_chat_histories")

    def to_dict(self):
        """Convert to dictionary for JSON serialization."""
        return {
            'id': str(self.id),
            'user_id': str(self.user_id) if self.user_id else None,
            'recId': self.rec_id,  # Use camelCase for frontend compatibility
            'title': self.title,
            'messages': self.messages,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None,
        }


